# fly.toml app configuration file generated for saunaspace-custom-checkout on 2023-12-05T08:50:54-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "saunaspace-custom-checkout"
primary_region = "ord"

[build]

[env]
PORT = "3000"
SHOPIFY_APP_URL = "https://saunaspace-custom-checkout.fly.dev/"
SHOPIFY_API_KEY = "e8327af6e8089f33c050252f55ef308d"
SCOPES = "write_products"


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
