# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "saunaspace-custom-checkout"
client_id = "e8327af6e8089f33c050252f55ef308d"
application_url = "https://saint-spiritual-endorsed-isbn.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://saint-spiritual-endorsed-isbn.trycloudflare.com/auth/callback",
  "https://saint-spiritual-endorsed-isbn.trycloudflare.com/auth/shopify/callback",
  "https://saint-spiritual-endorsed-isbn.trycloudflare.com/api/auth/callback",
  "https://saint-spiritual-endorsed-isbn.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "saunaspace-checkout.myshopify.com"
